# Generated by Django 6.0.3 on 2026-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('captain', 'Captain'), ('jury', 'Jury'), ('organizer', 'Organizer'), ('admin', 'Admin')], default='participant', max_length=20),
        ),
    ]
