# Generated by Django 6.0.3 on 2026-03-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_announcements_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('jury', 'Jury'), ('curator', 'Curator'), ('organizer', 'Organizer'), ('admin', 'Admin')], default='participant', max_length=20),
        ),
    ]
