# Generated by Django 6.0.3 on 2026-03-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_convert_curators_to_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('participant', 'РЈС‡Р°СЃРЅРёРє'), ('jury', 'Р–СѓСЂС–'), ('organizer', 'РћСЂРіР°РЅС–Р·Р°С‚РѕСЂ'), ('admin', 'РђРґРјС–РЅС–СЃС‚СЂР°С‚РѕСЂ')], default='participant', max_length=20),
        ),
    ]
