# Generated by Django 6.0.3 on 2026-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('participant', 'Учасник'), ('jury', 'Журі'), ('organizer', 'Організатор'), ('admin', 'Адміністратор')], default='participant', max_length=20),
        ),
    ]
