# Generated by Django 6.0.3 on 2026-03-12 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.URLField(verbose_name='GitHub посилання')),
                ('video_link', models.URLField(verbose_name='Відео посилання')),
                ('live_demo', models.URLField(blank=True, null=True, verbose_name='Live demo посилання')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис рішення')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Час подання')),
                ('is_final', models.BooleanField(default=False, verbose_name='Фінальна версія')),
            ],
            options={
                'verbose_name': 'Надіслана робота',
                'verbose_name_plural': 'Надіслані роботи',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва команди')),
                ('captain_name', models.CharField(max_length=255, verbose_name="Ім'я капітана")),
                ('captain_email', models.EmailField(max_length=254, verbose_name='Email капітана')),
                ('school', models.CharField(blank=True, max_length=255, null=True, verbose_name='Школа')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JuryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Член журі')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='tournament.submission', verbose_name='Робота')),
            ],
            options={
                'verbose_name': 'Призначення журі',
                'verbose_name_plural': 'Призначення журі',
                'ordering': ['jury_user', 'submission'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_backend', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка backend')),
                ('score_frontend', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка frontend')),
                ('score_functionality', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка функціональності')),
                ('score_ux', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка UX')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='Час оцінювання')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='tournament.juryassignment', verbose_name='Призначення журі')),
            ],
            options={
                'verbose_name': 'Оцінювання',
                'verbose_name_plural': 'Оцінювання',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва завдання')),
                ('description', models.TextField(verbose_name='Опис')),
                ('requirements', models.TextField(verbose_name='Вимоги')),
                ('must_have', models.TextField(verbose_name="Обов'язково має бути")),
                ('start_time', models.DateTimeField(verbose_name='Час початку')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Активне'), ('submission_closed', 'Прийом рішень завершено'), ('evaluated', 'Оцінено')], default='draft', max_length=30, verbose_name='Статус')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['start_time', 'title'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournament.task', verbose_name='Завдання'),
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournament.team', verbose_name='Команда'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Учасники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('start_date', models.DateTimeField(verbose_name='Дата початку')),
                ('registration_start', models.DateTimeField(verbose_name='Початок реєстрації')),
                ('registration_end', models.DateTimeField(verbose_name='Завершення реєстрації')),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна кількість команд')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('registration', 'Реєстрація'), ('running', 'Проводиться'), ('finished', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments_created', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
            ],
            options={
                'verbose_name': 'Турнір',
                'verbose_name_plural': 'Турніри',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.tournament', verbose_name='Турнір'),
        ),
        migrations.AddField(
            model_name='task',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tournament.tournament', verbose_name='Турнір'),
        ),
        migrations.AddConstraint(
            model_name='juryassignment',
            constraint=models.UniqueConstraint(fields=('jury_user', 'submission'), name='unique_jury_per_submission'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('team', 'task'), name='unique_submission_per_team_task'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_team_name_per_tournament'),
        ),
    ]
