# Generated by Django 6.0.3 on 2026-03-14 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_team_captain_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
            ],
            options={
                'verbose_name': 'Реєстрація команди на турнір',
                'verbose_name_plural': 'Реєстрації команд на турніри',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_name_per_tournament',
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_teams', to=settings.AUTH_USER_MODEL, verbose_name='Користувач-капітан'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Зареєстровано користувачем'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament.team', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament.tournament', verbose_name='Турнір'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(fields=('tournament', 'team'), name='unique_team_per_tournament'),
        ),
    ]
