# Generated by Django 6.0.3 on 2026-03-23 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournament_registration_fields_and_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='jury_users',
            field=models.ManyToManyField(blank=True, related_name='jury_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Призначене журі'),
        ),
    ]
