# Generated by Django 6.0.3 on 2026-03-24 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_registration_members_from_form_answers(apps, schema_editor):
    TournamentRegistration = apps.get_model("tournament", "TournamentRegistration")
    RegistrationMember = apps.get_model("tournament", "RegistrationMember")
    CustomUser = apps.get_model("users", "CustomUser")

    registration_members = []
    for registration in TournamentRegistration.objects.all():
        for value in (registration.form_answers or {}).values():
            if not isinstance(value, list):
                continue
            for item in value:
                if not isinstance(item, dict):
                    continue
                email = (item.get("email") or "").strip().lower()
                full_name = (item.get("full_name") or "").strip()
                if not email or not full_name:
                    continue
                linked_user = CustomUser.objects.filter(email__iexact=email).first()
                registration_members.append(
                    RegistrationMember(
                        registration_id=registration.id,
                        user_id=linked_user.id if linked_user else None,
                        full_name=full_name,
                        email=email,
                    )
                )

    if registration_members:
        RegistrationMember.objects.bulk_create(
            registration_members,
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_tournament_jury_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Учасник заявки',
                'verbose_name_plural': 'Учасники заявок',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Чернетка'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершення реєстрації'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Початок реєстрації'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('team', 'email'), name='unique_participant_email_per_team'),
        ),
        migrations.AddField(
            model_name='registrationmember',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournament.tournamentregistration', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='registrationmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_memberships', to=settings.AUTH_USER_MODEL, verbose_name="Пов'язаний користувач"),
        ),
        migrations.AddConstraint(
            model_name='registrationmember',
            constraint=models.UniqueConstraint(fields=('registration', 'email'), name='unique_registration_member_email'),
        ),
        migrations.RunPython(copy_registration_members_from_form_answers, migrations.RunPython.noop),
    ]
