# Generated by Django 6.0.3 on 2026-03-25 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_registrationmember_alter_tournament_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='curator_users',
            field=models.ManyToManyField(blank=True, related_name='curated_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Призначені куратори'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст оголошення')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата створення')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tournament.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('participant', 'Учасник'), ('winner', 'Переможець')], db_index=True, max_length=20, verbose_name='Тип сертифіката')),
                ('recipient_name', models.CharField(max_length=255, verbose_name="Ім'я отримувача")),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email отримувача')),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата видачі')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates_issued', to=settings.AUTH_USER_MODEL, verbose_name='Видав користувач')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_received', to=settings.AUTH_USER_MODEL, verbose_name='Користувач-отримувач')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='tournament.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tournament.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'certificate_type', 'recipient_email'), name='unique_certificate_per_tournament_type_email')],
            },
        ),
    ]
