# Generated by Django 6.0.3 on 2026-03-25 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournament_curator_users_announcement_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('participant', 'Учасник'), ('winner', 'Переможець')], db_index=True, max_length=20, verbose_name='Тип сертифіката')),
                ('background_image', models.ImageField(upload_to='certificate_templates/', verbose_name='Шаблон сертифіката')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата завантаження')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='tournament.tournament', verbose_name='Турнір')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_certificate_templates', to=settings.AUTH_USER_MODEL, verbose_name='Завантажив користувач')),
            ],
            options={
                'verbose_name': 'Шаблон сертифіката',
                'verbose_name_plural': 'Шаблони сертифікатів',
                'ordering': ['-created_at'],
            },
        ),
    ]
