# Generated by Django 6.0.3 on 2026-03-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_certificatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='team',
            name='viber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Viber'),
        ),
    ]
