# Generated by Django 6.0.3 on 2026-03-26 13:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_team_discord_team_viber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'РћРіРѕР»РѕС€РµРЅРЅСЏ', 'verbose_name_plural': 'РћРіРѕР»РѕС€РµРЅРЅСЏ'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at'], 'verbose_name': 'РЎРµСЂС‚РёС„С–РєР°С‚', 'verbose_name_plural': 'РЎРµСЂС‚РёС„С–РєР°С‚Рё'},
        ),
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'РЁР°Р±Р»РѕРЅ СЃРµСЂС‚РёС„С–РєР°С‚Р°', 'verbose_name_plural': 'РЁР°Р±Р»РѕРЅРё СЃРµСЂС‚РёС„С–РєР°С‚С–РІ'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['-evaluated_at'], 'verbose_name': 'РћС†С–РЅСЋРІР°РЅРЅСЏ', 'verbose_name_plural': 'РћС†С–РЅСЋРІР°РЅРЅСЏ'},
        ),
        migrations.AlterModelOptions(
            name='juryassignment',
            options={'ordering': ['jury_user', 'submission'], 'verbose_name': 'РџСЂРёР·РЅР°С‡РµРЅРЅСЏ Р¶СѓСЂС–', 'verbose_name_plural': 'РџСЂРёР·РЅР°С‡РµРЅРЅСЏ Р¶СѓСЂС–'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['full_name'], 'verbose_name': 'РЈС‡Р°СЃРЅРёРє', 'verbose_name_plural': 'РЈС‡Р°СЃРЅРёРєРё'},
        ),
        migrations.AlterModelOptions(
            name='registrationmember',
            options={'ordering': ['full_name'], 'verbose_name': 'РЈС‡Р°СЃРЅРёРє Р·Р°СЏРІРєРё', 'verbose_name_plural': 'РЈС‡Р°СЃРЅРёРєРё Р·Р°СЏРІРѕРє'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'РќР°РґС–СЃР»Р°РЅР° СЂРѕР±РѕС‚Р°', 'verbose_name_plural': 'РќР°РґС–СЃР»Р°РЅС– СЂРѕР±РѕС‚Рё'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title'], 'verbose_name': 'Р—Р°РІРґР°РЅРЅСЏ', 'verbose_name_plural': 'Р—Р°РІРґР°РЅРЅСЏ'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'РљРѕРјР°РЅРґР°', 'verbose_name_plural': 'РљРѕРјР°РЅРґРё'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-start_date', 'name'], 'verbose_name': 'РўСѓСЂРЅС–СЂ', 'verbose_name_plural': 'РўСѓСЂРЅС–СЂРё'},
        ),
        migrations.AlterModelOptions(
            name='tournamentregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Р\xa0РµС”СЃС‚СЂР°С†С–СЏ РєРѕРјР°РЅРґРё РЅР° С‚СѓСЂРЅС–СЂ', 'verbose_name_plural': 'Р\xa0РµС”СЃС‚СЂР°С†С–С— РєРѕРјР°РЅРґ РЅР° С‚СѓСЂРЅС–СЂРё'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Р”Р°С‚Р° СЃС‚РІРѕСЂРµРЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='РЎС‚РІРѕСЂРµРЅРѕ РєРѕСЂРёСЃС‚СѓРІР°С‡РµРј'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(verbose_name='РўРµРєСЃС‚ РѕРіРѕР»РѕС€РµРЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Р—Р°РіРѕР»РѕРІРѕРє'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tournament.tournament', verbose_name='РўСѓСЂРЅС–СЂ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('participant', 'РЈС‡Р°СЃРЅРёРє'), ('winner', 'РџРµСЂРµРјРѕР¶РµС†СЊ')], db_index=True, max_length=20, verbose_name='РўРёРї СЃРµСЂС‚РёС„С–РєР°С‚Р°'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Р”Р°С‚Р° РІРёРґР°С‡С–'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates_issued', to=settings.AUTH_USER_MODEL, verbose_name='Р’РёРґР°РІ РєРѕСЂРёСЃС‚СѓРІР°С‡'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='recipient_email',
            field=models.EmailField(max_length=254, verbose_name='Email РѕС‚СЂРёРјСѓРІР°С‡Р°'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='recipient_name',
            field=models.CharField(max_length=255, verbose_name="Р†Рј'СЏ РѕС‚СЂРёРјСѓРІР°С‡Р°"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_received', to=settings.AUTH_USER_MODEL, verbose_name='РљРѕСЂРёСЃС‚СѓРІР°С‡-РѕС‚СЂРёРјСѓРІР°С‡'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='tournament.team', verbose_name='РљРѕРјР°РЅРґР°'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tournament.tournament', verbose_name='РўСѓСЂРЅС–СЂ'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(upload_to='certificate_templates/', verbose_name='РЁР°Р±Р»РѕРЅ СЃРµСЂС‚РёС„С–РєР°С‚Р°'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='certificate_type',
            field=models.CharField(choices=[('participant', 'РЈС‡Р°СЃРЅРёРє'), ('winner', 'РџРµСЂРµРјРѕР¶РµС†СЊ')], db_index=True, max_length=20, verbose_name='РўРёРї СЃРµСЂС‚РёС„С–РєР°С‚Р°'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Р”Р°С‚Р° Р·Р°РІР°РЅС‚Р°Р¶РµРЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='tournament.tournament', verbose_name='РўСѓСЂРЅС–СЂ'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_certificate_templates', to=settings.AUTH_USER_MODEL, verbose_name='Р—Р°РІР°РЅС‚Р°Р¶РёРІ РєРѕСЂРёСЃС‚СѓРІР°С‡'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='tournament.juryassignment', verbose_name='РџСЂРёР·РЅР°С‡РµРЅРЅСЏ Р¶СѓСЂС–'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='РљРѕРјРµРЅС‚Р°СЂ'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р§Р°СЃ РѕС†С–РЅСЋРІР°РЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score_backend',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='РћС†С–РЅРєР° backend'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score_frontend',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='РћС†С–РЅРєР° frontend'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score_functionality',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='РћС†С–РЅРєР° С„СѓРЅРєС†С–РѕРЅР°Р»СЊРЅРѕСЃС‚С–'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score_ux',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='РћС†С–РЅРєР° UX'),
        ),
        migrations.AlterField(
            model_name='juryassignment',
            name='jury_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Р§Р»РµРЅ Р¶СѓСЂС–'),
        ),
        migrations.AlterField(
            model_name='juryassignment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='tournament.submission', verbose_name='Р\xa0РѕР±РѕС‚Р°'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='РџР†Р‘'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.team', verbose_name='РљРѕРјР°РЅРґР°'),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='РџР†Р‘'),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournament.tournamentregistration', verbose_name='Р—Р°СЏРІРєР°'),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_memberships', to=settings.AUTH_USER_MODEL, verbose_name="РџРѕРІ'СЏР·Р°РЅРёР№ РєРѕСЂРёСЃС‚СѓРІР°С‡"),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='РћРїРёСЃ СЂС–С€РµРЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='github_link',
            field=models.URLField(verbose_name='GitHub РїРѕСЃРёР»Р°РЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Р¤С–РЅР°Р»СЊРЅР° РІРµСЂСЃС–СЏ'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='live_demo',
            field=models.URLField(blank=True, null=True, verbose_name='Демо РїРѕСЃРёР»Р°РЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р§Р°СЃ РїРѕРґР°РЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournament.task', verbose_name='Р—Р°РІРґР°РЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournament.team', verbose_name='РљРѕРјР°РЅРґР°'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='video_link',
            field=models.URLField(verbose_name='Р’С–РґРµРѕ РїРѕСЃРёР»Р°РЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='РЎС‚РІРѕСЂРµРЅРѕ РєРѕСЂРёСЃС‚СѓРІР°С‡РµРј'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='РћРїРёСЃ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Р§РµСЂРЅРµС‚РєР°'),
        ),
        migrations.AlterField(
            model_name='task',
            name='must_have',
            field=models.TextField(verbose_name="РћР±РѕРІ'СЏР·РєРѕРІРѕ РјР°С” Р±СѓС‚Рё"),
        ),
        migrations.AlterField(
            model_name='task',
            name='official_solution',
            field=models.TextField(blank=True, null=True, verbose_name='РћС„С–С†С–Р№РЅР° РІС–РґРїРѕРІС–РґСЊ / СЂРѕР·Р±С–СЂ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='requirements',
            field=models.TextField(verbose_name='Р’РёРјРѕРіРё'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='РќР°Р·РІР° Р·Р°РІРґР°РЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tournament.tournament', verbose_name='РўСѓСЂРЅС–СЂ'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_email',
            field=models.EmailField(max_length=254, verbose_name='Email РєР°РїС–С‚Р°РЅР°'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_name',
            field=models.CharField(max_length=255, verbose_name="Р†Рј'СЏ РєР°РїС–С‚Р°РЅР°"),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_teams', to=settings.AUTH_USER_MODEL, verbose_name='РљРѕСЂРёСЃС‚СѓРІР°С‡-РєР°РїС–С‚Р°РЅ'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р”Р°С‚Р° СЃС‚РІРѕСЂРµРЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='team',
            name='discord',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Діскорд'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='РќР°Р·РІР° РєРѕРјР°РЅРґРё'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='РЁРєРѕР»Р°'),
        ),
        migrations.AlterField(
            model_name='team',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='team',
            name='viber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вайбер'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments_created', to=settings.AUTH_USER_MODEL, verbose_name='РЎС‚РІРѕСЂРµРЅРѕ РєРѕСЂРёСЃС‚СѓРІР°С‡РµРј'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='curator_users',
            field=models.ManyToManyField(blank=True, related_name='curated_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='РџСЂРёР·РЅР°С‡РµРЅС– РєСѓСЂР°С‚РѕСЂРё'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(verbose_name='РћРїРёСЃ'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Р”Р°С‚Р° Р·Р°РІРµСЂС€РµРЅРЅСЏ'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Р§РµСЂРЅРµС‚РєР°'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='jury_users',
            field=models.ManyToManyField(blank=True, related_name='jury_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='РџСЂРёР·РЅР°С‡РµРЅРµ Р¶СѓСЂС–'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_team_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='РњР°РєСЃРёРјР°Р»СЊРЅР° РєС–Р»СЊРєС–СЃС‚СЊ Р»СЋРґРµР№ Сѓ РєРѕРјР°РЅРґС–'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='РњР°РєСЃРёРјР°Р»СЊРЅР° РєС–Р»СЊРєС–СЃС‚СЊ РєРѕРјР°РЅРґ'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='min_team_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='РњС–РЅС–РјР°Р»СЊРЅР° РєС–Р»СЊРєС–СЃС‚СЊ Р»СЋРґРµР№ Сѓ РєРѕРјР°РЅРґС–'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=255, verbose_name='РќР°Р·РІР°'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Р—Р°РІРµСЂС€РµРЅРЅСЏ СЂРµС”СЃС‚СЂР°С†С–С—'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_fields_config',
            field=models.JSONField(blank=True, default=list, verbose_name='РџРѕР»СЏ С„РѕСЂРјРё СЂРµС”СЃС‚СЂР°С†С–С—'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_form_description',
            field=models.TextField(blank=True, default='', verbose_name='РћРїРёСЃ С„РѕСЂРјРё СЂРµС”СЃС‚СЂР°С†С–С— РєРѕРјР°РЅРґРё'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='РџРѕС‡Р°С‚РѕРє СЂРµС”СЃС‚СЂР°С†С–С—'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Р”Р°С‚Р° РїРѕС‡Р°С‚РєСѓ'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р”Р°С‚Р° СЂРµС”СЃС‚СЂР°С†С–С—'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='form_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Р’С–РґРїРѕРІС–РґС– РЅР° РїРѕР»СЏ С„РѕСЂРјРё'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Р—Р°СЂРµС”СЃС‚СЂРѕРІР°РЅРѕ РєРѕСЂРёСЃС‚СѓРІР°С‡РµРј'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'РћС‡С–РєСѓС”'), ('approved', 'РЎС…РІР°Р»РµРЅРѕ'), ('rejected', 'Р’С–РґС…РёР»РµРЅРѕ')], db_index=True, default='pending', max_length=20, verbose_name='РЎС‚Р°С‚СѓСЃ Р·Р°СЏРІРєРё'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament.team', verbose_name='РљРѕРјР°РЅРґР°'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament.tournament', verbose_name='РўСѓСЂРЅС–СЂ'),
        ),
    ]
