# Generated by Django 6.0.3 on 2026-03-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_alter_announcement_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='curator_users',
        ),
    ]
