# Generated by Django 6.0.3 on 2026-04-12 09:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_task_submission_format_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оголошення', 'verbose_name_plural': 'Оголошення'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Сертифікат', 'verbose_name_plural': 'Сертифікати'},
        ),
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Шаблон сертифіката', 'verbose_name_plural': 'Шаблони сертифікатів'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['-evaluated_at'], 'verbose_name': 'Оцінювання', 'verbose_name_plural': 'Оцінювання'},
        ),
        migrations.AlterModelOptions(
            name='juryassignment',
            options={'ordering': ['jury_user', 'submission'], 'verbose_name': 'Призначення журі', 'verbose_name_plural': 'Призначення журі'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['full_name'], 'verbose_name': 'Учасник', 'verbose_name_plural': 'Учасники'},
        ),
        migrations.AlterModelOptions(
            name='registrationmember',
            options={'ordering': ['full_name'], 'verbose_name': 'Учасник заявки', 'verbose_name_plural': 'Учасники заявок'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Надіслана робота', 'verbose_name_plural': 'Надіслані роботи'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title'], 'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команди'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-start_date', 'name'], 'verbose_name': 'Турнір', 'verbose_name_plural': 'Турніри'},
        ),
        migrations.AlterModelOptions(
            name='tournamentregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Реєстрація команди на турнір', 'verbose_name_plural': 'Реєстрації команд на турніри'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_banners/', verbose_name='Банер турніру'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(verbose_name='Текст оголошення'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tournament.tournament', verbose_name='Турнір'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('participant', 'Учасник'), ('winner', 'Переможець')], db_index=True, max_length=20, verbose_name='Тип сертифіката'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата видачі'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates_issued', to=settings.AUTH_USER_MODEL, verbose_name='Видав користувач'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='recipient_email',
            field=models.EmailField(max_length=254, verbose_name='Email отримувача'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='recipient_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я отримувача"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_received', to=settings.AUTH_USER_MODEL, verbose_name='Користувач-отримувач'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='tournament.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tournament.tournament', verbose_name='Турнір'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(upload_to='certificate_templates/', verbose_name='Шаблон сертифіката'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='certificate_type',
            field=models.CharField(choices=[('participant', 'Учасник'), ('winner', 'Переможець')], db_index=True, max_length=20, verbose_name='Тип сертифіката'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата завантаження'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='tournament.tournament', verbose_name='Турнір'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_certificate_templates', to=settings.AUTH_USER_MODEL, verbose_name='Завантажив користувач'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='tournament.juryassignment', verbose_name='Призначення журі'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час оцінювання'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score_backend',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка backend'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score_frontend',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка frontend'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score_functionality',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка функціональності'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score_ux',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка UX'),
        ),
        migrations.AlterField(
            model_name='juryassignment',
            name='jury_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Член журі'),
        ),
        migrations.AlterField(
            model_name='juryassignment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='tournament.submission', verbose_name='Робота'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournament.tournamentregistration', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='registrationmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_memberships', to=settings.AUTH_USER_MODEL, verbose_name="Пов'язаний користувач"),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис рішення'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Фінальна версія'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='live_demo',
            field=models.URLField(blank=True, null=True, verbose_name='Демо посилання'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час подання'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournament.task', verbose_name='Завдання'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournament.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Чернетка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='must_have',
            field=models.TextField(verbose_name="Обов'язково має бути"),
        ),
        migrations.AlterField(
            model_name='task',
            name='official_solution',
            field=models.TextField(blank=True, null=True, verbose_name='Офіційна відповідь / розбір'),
        ),
        migrations.AlterField(
            model_name='task',
            name='requirements',
            field=models.TextField(verbose_name='Вимоги'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва завдання'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tournament.tournament', verbose_name='Турнір'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_email',
            field=models.EmailField(max_length=254, verbose_name='Email контактної особи'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я контактної особи"),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_teams', to=settings.AUTH_USER_MODEL, verbose_name="Прив'язаний користувач"),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва команди'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments_created', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Чернетка'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='jury_users',
            field=models.ManyToManyField(blank=True, related_name='jury_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Призначене журі'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_team_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна кількість людей у команді'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна кількість команд'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='min_team_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мінімальна кількість людей у команді'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершення реєстрації'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_fields_config',
            field=models.JSONField(blank=True, default=list, verbose_name='Поля форми реєстрації'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_form_description',
            field=models.TextField(blank=True, default='', verbose_name='Опис форми реєстрації команди'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Початок реєстрації'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='form_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Відповіді на поля форми'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Зареєстровано користувачем'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament.tournament', verbose_name='Турнір'),
        ),
    ]
