from django.urls import path
from .views import (
    home,
    archive_view,
    register_view,
    register_success_view,
    verify_email_view,
    login_view,
    logout_view,
    redirect_by_role,
    public_tournament_detail,
    profile_view,
    messages_view,
    certificates_view,
    my_team_view,
    admin_dashboard,
    admin_users,
    admin_active_tournaments,
    admin_inactive_tournaments,
    admin_teams,
    admin_registrations,
    admin_submissions,
    admin_announcements,
    admin_certificates,
    organizer_dashboard,
    create_user_by_admin,
    approve_user,
    update_user_role,
    delete_user,
    approve_registration,
    reject_registration,
    create_tournament,
    edit_tournament,
    delete_tournament,
    start_tournament_now,
    finish_tournament_now,
    finish_evaluation_now,
    issue_participant_certificates,
    issue_winner_certificates,
    export_tournament_results_csv,
    download_certificate_pdf,
    create_task,
    edit_task,
    delete_task,
    jury_dashboard,
    jury_tournament_detail,
    submit_evaluation,
    participant_dashboard,
    create_team,
    register_team_for_tournament,
    team_detail,
    edit_team,
    team_participants,
    add_participant,
    delete_participant,
    delete_team,
    leave_team,
    tournament_tasks,
    tournament_leaderboard,
    team_results,
    submit_solution,
)

urlpatterns = [
    path('', home, name='home'),
    path('archive/', archive_view, name='archive'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('register/success/', register_success_view, name='register_success'),
    path('verify-email/<uidb64>/<token>/', verify_email_view, name='verify_email'),
    path('logout/', logout_view, name='logout'),
    path('redirect/', redirect_by_role, name='redirect_by_role'),
    path('profile/', profile_view, name='profile'),
    path('messages/', messages_view, name='messages'),
    path('certificates/', certificates_view, name='certificates'),
    path('my-team/', my_team_view, name='my_team'),

    path('admin-dashboard/', admin_dashboard, name='admin_dashboard'),
    path('dashboard/users/', admin_users, name='admin_users'),
    path('dashboard/tournaments/active/', admin_active_tournaments, name='admin_active_tournaments'),
    path('dashboard/tournaments/inactive/', admin_inactive_tournaments, name='admin_inactive_tournaments'),
    path('dashboard/teams/', admin_teams, name='admin_teams'),
    path('dashboard/registrations/', admin_registrations, name='admin_registrations'),
    path('dashboard/submissions/', admin_submissions, name='admin_submissions'),
    path('dashboard/announcements/', admin_announcements, name='admin_announcements'),
    path('dashboard/certificates/', admin_certificates, name='admin_certificates'),
    path('organizer-dashboard/', organizer_dashboard, name='organizer_dashboard'),
    path('admin-create-user/', create_user_by_admin, name='create_user_by_admin'),
    path('approve-user/<int:user_id>/', approve_user, name='approve_user'),
    path('update-user-role/<int:user_id>/', update_user_role, name='update_user_role'),
    path('delete-user/<int:user_id>/', delete_user, name='delete_user'),
    path('approve-registration/<int:registration_id>/', approve_registration, name='approve_registration'),
    path('reject-registration/<int:registration_id>/', reject_registration, name='reject_registration'),
    path('create-tournament/', create_tournament, name='create_tournament'),
    path('edit-tournament/<int:tournament_id>/', edit_tournament, name='edit_tournament'),
    path('delete-tournament/<int:tournament_id>/', delete_tournament, name='delete_tournament'),
    path('tournament/<int:tournament_id>/start-now/', start_tournament_now, name='start_tournament_now'),
    path('tournament/<int:tournament_id>/finish-now/', finish_tournament_now, name='finish_tournament_now'),
    path('tournament/<int:tournament_id>/finish-evaluation/', finish_evaluation_now, name='finish_evaluation_now'),
    path('tournament/<int:tournament_id>/issue-participant-certificates/', issue_participant_certificates, name='issue_participant_certificates'),
    path('tournament/<int:tournament_id>/issue-winner-certificates/', issue_winner_certificates, name='issue_winner_certificates'),
    path('tournament/<int:tournament_id>/results-export.csv', export_tournament_results_csv, name='export_tournament_results_csv'),
    path('certificate/<int:certificate_id>/download/', download_certificate_pdf, name='download_certificate_pdf'),
    path('create-task/', create_task, name='create_task'),
    path('tournament/<int:tournament_id>/create-task/', create_task, name='create_tournament_task'),
    path('tournament/<int:tournament_id>/', public_tournament_detail, name='public_tournament_detail'),
    path('edit-task/<int:task_id>/', edit_task, name='edit_task'),
    path('delete-task/<int:task_id>/', delete_task, name='delete_task'),

    path('jury-dashboard/', jury_dashboard, name='jury_dashboard'),
    path('jury-dashboard/tournament/<int:tournament_id>/', jury_tournament_detail, name='jury_tournament_detail'),
    path('jury/submission/<int:submission_id>/evaluate/', submit_evaluation, name='submit_evaluation'),

    path('participant-dashboard/', participant_dashboard, name='participant_dashboard'),
    path('create-team/', create_team, name='create_team'),
    path('register-team-for-tournament/<int:tournament_id>/', register_team_for_tournament, name='register_team_for_tournament'),

    path('team/<int:team_id>/', team_detail, name='team_detail'),
    path('team/<int:team_id>/edit/', edit_team, name='edit_team'),
    path('team/<int:team_id>/participants/', team_participants, name='team_participants'),
    path('team/<int:team_id>/add-participant/', add_participant, name='add_participant'),
    path('team/<int:team_id>/participant/<int:participant_id>/delete/', delete_participant, name='delete_participant'),
    path('team/<int:team_id>/delete/', delete_team, name='delete_team'),
    path('team/<int:team_id>/leave/', leave_team, name='leave_team'),
    path('tournament/<int:tournament_id>/tasks/', tournament_tasks, name='tournament_tasks'),
    path('tournament/<int:tournament_id>/leaderboard/', tournament_leaderboard, name='tournament_leaderboard'),
    path('team/<int:team_id>/results/', team_results, name='team_results'),
    path('task/<int:task_id>/submit/', submit_solution, name='submit_solution'),
]
