from django.urls import path
from .views import (
    home,
    register_view,
    login_view,
    logout_view,
    redirect_by_role,
    admin_dashboard,
    create_user_by_admin,
    approve_user,
    update_user_role,
    delete_user,
    approve_registration,
    reject_registration,
    create_tournament,
    edit_tournament,
    delete_tournament,
    create_task,
    edit_task,
    delete_task,
    jury_dashboard,
    jury_tournament_detail,
    submit_evaluation,
    participant_dashboard,
    create_team,
    register_team_for_tournament,
    team_detail,
    team_participants,
    add_participant,
    delete_participant,
    delete_team,
    leave_team,
    tournament_tasks,
    tournament_leaderboard,
    team_results,
    submit_solution,
)

urlpatterns = [
    path('', home, name='home'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('redirect/', redirect_by_role, name='redirect_by_role'),

    path('admin-dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin-create-user/', create_user_by_admin, name='create_user_by_admin'),
    path('approve-user/<int:user_id>/', approve_user, name='approve_user'),
    path('update-user-role/<int:user_id>/', update_user_role, name='update_user_role'),
    path('delete-user/<int:user_id>/', delete_user, name='delete_user'),
    path('approve-registration/<int:registration_id>/', approve_registration, name='approve_registration'),
    path('reject-registration/<int:registration_id>/', reject_registration, name='reject_registration'),
    path('create-tournament/', create_tournament, name='create_tournament'),
    path('edit-tournament/<int:tournament_id>/', edit_tournament, name='edit_tournament'),
    path('delete-tournament/<int:tournament_id>/', delete_tournament, name='delete_tournament'),
    path('create-task/', create_task, name='create_task'),
    path('tournament/<int:tournament_id>/create-task/', create_task, name='create_tournament_task'),
    path('edit-task/<int:task_id>/', edit_task, name='edit_task'),
    path('delete-task/<int:task_id>/', delete_task, name='delete_task'),

    path('jury-dashboard/', jury_dashboard, name='jury_dashboard'),
    path('jury-dashboard/tournament/<int:tournament_id>/', jury_tournament_detail, name='jury_tournament_detail'),
    path('jury/submission/<int:submission_id>/evaluate/', submit_evaluation, name='submit_evaluation'),

    path('participant-dashboard/', participant_dashboard, name='participant_dashboard'),
    path('create-team/', create_team, name='create_team'),
    path('register-team-for-tournament/<int:tournament_id>/', register_team_for_tournament, name='register_team_for_tournament'),

    path('team/<int:team_id>/', team_detail, name='team_detail'),
    path('team/<int:team_id>/participants/', team_participants, name='team_participants'),
    path('team/<int:team_id>/add-participant/', add_participant, name='add_participant'),
    path('team/<int:team_id>/participant/<int:participant_id>/delete/', delete_participant, name='delete_participant'),
    path('team/<int:team_id>/delete/', delete_team, name='delete_team'),
    path('team/<int:team_id>/leave/', leave_team, name='leave_team'),
    path('tournament/<int:tournament_id>/tasks/', tournament_tasks, name='tournament_tasks'),
    path('tournament/<int:tournament_id>/leaderboard/', tournament_leaderboard, name='tournament_leaderboard'),
    path('team/<int:team_id>/results/', team_results, name='team_results'),
    path('task/<int:task_id>/submit/', submit_solution, name='submit_solution'),
]
